# Overview {#over}

My goal is to foster an environment of consistent scientific excellence and personal & professional development for all lab members, allowing you to reach your full potential whilst at the same time doing important science. I want to prepare you for whatever you will do professionally after your stay in this lab. An important aspect I procure is a good and healty group environment, overall staff health (mental and physical) and sense of accomplishment. 


## Mission Statement

* Rigorous: All work conducted in the lab should be rigorously-conducted. We take our science very seriously, and we ensure that the work we conduct is of the highest quality. As part of this, we follow principles of Open Science & Reproducibility, ensure that our studies are designed with sufficient statistical power to be informative, and hold ourselves to the strictest of ethical standards. As part of this rigour, we ensure that our studies are addressing important and novel questions.

* Fundamental Research: Science typically falls into one of two categories: Fundamental (or “basic” / “pure”) research, and Applied research. Fundamental research aims to improve scientific theories, generate new ideas and knowledge, and discover new empirical phenomena, without the promise of an immediate application of this knowledge. It is often referred to as the pursuit of knowledge for its own sake. An important part of our research strategy is to conduct fundamental research into substance use and addiction, as well as other neuropsychiatric conditions.

* Neuroimaging:

* Addiction: 

* Applied Research: 
