--- 
title: "GarzaLab Manual and Code of Conduct"
author: "Eduardo A. Garza-Villarreal"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: garzalab/garzalab-manual
url: 'https://github.com/GarzaLab/garzalab-manual'
description: "This is the manual and code of conduct for all staff and students at the GarzaLab"
---

# Welcome

Welcome to the Neuroimaging and Psychiatry Lab aka GarzaLab. 
This is a walkthrough for new students and staff, as well as the place to find FAQs and the code of conduct. Hopefuly this manual with provide you with an idea of how the lab functions, provide clarity on my expectations on lab members and what you can expect from me.

All lab members will be expected to read this lab manual. The manual is a dynamic document, so some sections will be added and/or revised as the lab grows and develops. 

This manual was mostly inspired by the great [Grange-Lab manual](https://bookdown.org/JimGrange/Grange-lab-manual/intro.html). This manual is licence under a [CC Attribution 4.0 Licence](https://creativecommons.org/licenses/by/4.0/).

Let me know if you have any questions.

Kind regards

Eduardo A. Garza-Villarreal, MD, PhD
Lab Leader
egarza at comunidad.unam.mx
